.PHONY: build run test

build:
	go build -o main ./cmd/main

run:
	go run ./cmd/main/main.go

test:
	go test ./...

docker-build:
	docker build -t main .

docker-run:
	docker-compose up -d

clean:
	rm -f authapiands.sh